# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 96f448f0c0fd1e32b38e04c0abda4a25dac70df02acfd164027f0d5eb2e2a4d19c0bb73022a8acbaeb3d1586b6dd8228dce8652a99e093c2e8d8448d8c6d3be4

test:
  secret_key_base: 2231fda2ec072b472e8d0d4e97366db53ca3d59f0e7a8b1ab24d58cd055ff285f3a0adcf1408208e9eb92305c85fa5050916be2fa816ad6151f85375192da873

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
